import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/headers/NavBar";
import Providers from "./provider";
import Footer from "@/components/Footer/Footer";
import Head from "next/head";

// import {  ClerkProvider,} from '@clerk/nextjs'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Shopbite",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>  
          {/* <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
          <link rel="icon" href="/favicon.png" sizes="32x32" />
 </Head>
      <Providers> 
        <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-screen ">
        <NavBar/>
        </div>
      <main className="py-4 mb-20"> {children}</main>
      <Footer/>
      </body> </Providers>
    </html>
  );
}
